# Allow unauthorized users to access the client
clientAllowUnauthorized: true
# Allow unauthorized users to access the client
proxyAllowUnauthorized: false

server:
  port: 8686
spring:
  datasource:
    url: jdbc:sqlite:${user.dir}/config/ConfigDB.db
    driver-class-name: org.sqlite.JDBC
    #username: 登录账号
    #password: 登录密码
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
logging:
  level:    org.mirrentools.orion.mapper: debug  file:    path: ./logs
    