# 是否允许未登录用户访问客户端(Allow unauthorized users to access the client)
clientAllowUnauthorized: true
# 是否允许未登录用户使用代理请求(Allow unauthorized users to access the proxy)
proxyAllowUnauthorized: true
# 控制台显示的标题(Title displayed on the console)
orionConsoleTitle: Orion-API-Manager
# 控制台的欢迎语句(Welcome statement displayed on the console)
orionConsoleWelcome: Welcome to Orion-API-Manager

server:
  port: 8686
spring:
  datasource:
    url: jdbc:sqlite:${user.dir}/config/ConfigDB.db
    driver-class-name: org.sqlite.JDBC
    #username: 登录账号
    #password: 登录密码
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
logging:
  level:    org.mirrentools.orion.mapper: debug  file:    path: ./logs
    