# 是否允许未登录用户访问客户端(Allow unauthorized users to access the client)
clientAllowUnauthorized: true
# 是否允许未登录用户使用代理请求(Allow unauthorized users to access the proxy)
proxyAllowUnauthorized: true
# 控制台显示的标题(Title displayed on the console)
orionConsoleTitle: Orion-API-Manager
# 控制台的欢迎语句(Welcome statement displayed on the console)
orionConsoleWelcome: Welcome to Orion-API-Manager

server:
  port: 8686
spring:
  datasource:
    url: jdbc:mysql://10.0.0.79:3306/orion_api_manager?useUnicode=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver    druid:      validation-query: SELECT 1
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
logging:
  level:    org.mirrentools.orion.mapper: debug  file:    path: ./logs
    