# Allow unauthorized users to access the client
clientAllowUnauthorized: true
# Allow unauthorized users to access the client
proxyAllowUnauthorized: false

server:
  port: 8686
spring:
  datasource:
    url: jdbc:mysql://10.0.0.79:3306/orion_api_manager?useUnicode=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver    druid:      validation-query: SELECT 1
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
logging:
  level:    org.mirrentools.orion.mapper: debug  file:    path: ./logs
    